import "rxjs/add/operator/catch";
// import 'rxjs/add/operator/delay';
import "rxjs/add/operator/do";
// import 'rxjs/add/operator/finally';
import "rxjs/add/operator/map";
import "rxjs/add/operator/switchMap";
// import 'rxjs/add/operator/toPromise';
// import 'rxjs/add/observable/of';
// import 'rxjs/add/observable/fromPromise';
import "rxjs/add/observable/throw";
import "rxjs/add/observable/interval";
import "rxjs/add/observable/timer";
